stages:
  download_data:
    cmd: python src/data/download.py
    deps:
    - params.yaml
    - src/data/download.py
    outs:
    - data/raw_data/raw.csv
  split_data:
    cmd: python src/data/data_split.py
    deps:
    - data/raw_data/raw.csv
    - params.yaml
    - src/data/data_split.py
    outs:
    - data/split_data/
  normalize_data:
    cmd: python src/data/normalize.py
    deps:
    - data/split_data/X_test.csv
    - data/split_data/X_train.csv
    - params.yaml
    - src/data/normalize.py
    outs:
    - data/normalize_data
  gridsearch:
    cmd: python src/models/gridsearch.py
    deps:
    - data/normalize_data/X_train_scaled.csv
    - data/split_data/y_train.csv
    - params.yaml
    - src/models/gridsearch.py
    outs:
    - models/best_params.pkl
  train:
    cmd: python src/models/train.py
    deps:
    - data/normalize_data/X_train_scaled.csv
    - data/split_data/y_train.csv
    - models/best_params.pkl
    - params.yaml
    - src/models/train.py
    outs:
    - models/model.pkl
  evaluate:
    cmd: python src/models/evaluate.py
    deps:
    - data/normalize_data/X_test_scaled.csv
    - data/split_data/y_test.csv
    - models/model.pkl
    - params.yaml
    - src/models/evaluate.py
    metrics:
    - metrics/scores.json:
        cache: false
